//Require MATH module for sqrt function
require("MATH")
print("Hello World")
print ("Comments enabled")
$myVar = 12
print ("The value of $myVar is ", $myVar)
$name = input("What is your name? ")
print("Hello ",$name)//Look, inline comments
print ("The square root of 1823 is ", sqrt(1823))
print (sqrt(input("Give me a number to square root >")))
print ("This is a list ", [1,2, "Three"]);print("This is on the same line")
print ("Test");//Test;print("Please dont show up")

{

    print ("This is inside a code block")
    $name = input("Name again please >")
    print ("Hello again ", $name)

}

$myVar = 100
print ($myVar)
$myVar = $myVar + 100
print ($myVar + 100)

print("2 == 2 => ", 2==2)
